### ISSUE TITLE
PSP coverage tests fail to build on the MCP750/VxWorks 6.9 target

### ISSUE THREAD

**Issue by jphickey** [nasa/PSP#204]
**Describe the bug**
When building for MCP750 with all unit/coverage tests enabled, an error occurs:

```
In file included from /home/jphickey/cfecfs/github/psp/fsw/mcp750-vxworks/src/cfe_psp_exception.c:46:
/home/jphickey/cfecfs/github/psp/unit-test-coverage/ut-stubs/override_inc/arch/ppc/vxPpcLib.h:32:1: error: "_PPC_FPSCR_UE" redefined
In file included from /opt/WindRiver/vxworks-6.9/target/h/types/vxArch.h:148,
                 from /opt/WindRiver/vxworks-6.9/target/h/types/vxANSI.h:65,
                 from /opt/WindRiver/vxworks-6.9/target/h/limits.h:42,
                 from /opt/WindRiver/gnu/4.3.3-vxworks-6.9/x86-linux2/bin/../../lib/gcc/powerpc-wrs-vxworks/4.3.3/include-fixed/limits.h:122,
                 from /opt/WindRiver/gnu/4.3.3-vxworks-6.9/x86-linux2/bin/../../lib/gcc/powerpc-wrs-vxworks/4.3.3/include-fixed/syslimits.h:7,
                 from /opt/WindRiver/gnu/4.3.3-vxworks-6.9/x86-linux2/bin/../../lib/gcc/powerpc-wrs-vxworks/4.3.3/include-fixed/limits.h:11,
                 from /home/jphickey/cfecfs/github/psp/unit-test-coverage/ut-stubs/inc/PCS_basetypes.h:26,
                 from /home/jphickey/cfecfs/github/psp/unit-test-coverage/ut-stubs/inc/PCS_stdio.h:5,
                 from /home/jphickey/cfecfs/github/psp/unit-test-coverage/ut-stubs/override_inc/stdio.h:15,
                 from /home/jphickey/cfecfs/github/psp/fsw/mcp750-vxworks/src/cfe_psp_exception.c:39:
/opt/WindRiver/vxworks-6.9/target/h/arch/ppc/archPpc.h:187:1: error: this is the location of the previous definition
```

**To Reproduce**
Prepare using `make SIMULATION=ppc-vxworks6.9 ENABLE_UNIT_TESTS=true prep` and sample_defs config
Then run `make`

**Expected behavior**
Build should succeed

**System observed on:**
`gs582w-cfelnx` build machine with MCP750 target

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by jphickey** [comment]
Dug into this - cause is that there is a conflict/duplication between system-provided macro definitions and the macro definitions that are being intentionally overridden by the coverage test environment.

- Coverage test environment overrides most system headers, but intentionally does _not_override `limits.h` or `stdint.h` because limit macros and fixed-width types need to be correct for the machine actually executing the coverage tests.
- But the VxWorks `limit.h` header implicitly - through a network of nested includes - includes a whole bunch of CPU-specific definitions, including e.g. `_PPC_FPSCR_UE` in this case.
