### PR TITLE
Fix #204, redefinition of macros in PPC vxworks unit test build

### LINKED ISSUE #204: PSP coverage tests fail to build on the MCP750/VxWorks 6.9 target
**Describe the bug**
When building for MCP750 with all unit/coverage tests enabled, an error occurs:

```
In file included from /home/jphickey/cfecfs/github/psp/fsw/mcp750-vxworks/src/cfe_psp_exception.c:46:
/home/jphickey/cfecfs/github/psp/unit-test-coverage/ut-stubs/override_inc/arch/ppc/vxPpcLib.h:32:1: error: "_PPC_FPSCR_UE" redefined
In file included from /opt/WindRiver/vxworks-6.9/target/h/types/vxArch.h:148,
                 from /opt/WindRiver/vxworks-6.9/target/h/types/vxANSI.h:65,
                 from /opt/WindRiver/vxworks-6.9/target/h/limits.h:42,
                 from /opt/WindRiver/gnu/4.3.3-vxworks-6.9/x86-linux2/bin/../../lib/gcc/powerpc-wrs-vxworks/4.3.3/include-fixed/limits.h:122,
                 from /opt/WindRiver/gnu/4.3.3-vxworks-6.9/x86-linux2/bin/../../lib/gcc/powerpc-wrs-vxworks/4.3.3/include-fixed/syslimits.h:7,
                 from /opt/WindRiver/gnu/4.3.3-vxworks-6.9/x86-linux2/bin/../../lib/gcc/powerpc-wrs-vxworks/4.3.3/include-fixed/limits.h:11,
                 from /home/jphickey/cfecfs/github/psp/unit-test-coverage/ut-stubs/inc/PCS_basetypes.h:26,
                 from /home/jphickey/cfecfs/github/psp/unit-test-coverage/ut-stubs/inc/PCS_stdio.h:5,
                 from /home/jphickey/cfecfs/github/psp/unit-test-coverage/ut-stubs/override_inc/stdio.h:15,
                 from /home/jphickey/cfecfs/github/psp/fsw/mcp750-vxworks/src/cfe_psp_exception.c:39:
/opt/WindRiver/vxworks-6.9/target/h/arch/ppc/archPpc.h:187:1: error: this is the location of the previous definition
```

**To Reproduce**
Prepare using `make SIMULATION=ppc-vxworks6.9 ENABLE_UNIT_TESTS=true prep` and sample_defs config
Then run `make`

**Expected behavior**
Build should succeed

**System observed on:**
`gs582w-cfelnx` build machine with MCP750 target

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Fix #204
Resolves build error regarding redefinition of PPC macros in the coverage test, when building on the actual ppc/vxworks target.

This is due to the fact that the system limits.h file implicitly provides these PPC symbols.  It does not appear that there are
any current test cases that depend on values of these symbols.

**Testing performed**
Build verification only at this time (resolves compile error)

**Expected behavior changes**
None

**System(s) tested on**
GSFC vxworks build machine (gs582w-cfelnx)

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by astrogeco** [comment]
[CCB 2020-10-06](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-October-06-2020) APPROVED
